project:
  type: website
  output-dir: docs

website:
  title: "OWE CA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cyborg
    mainfont: arial
    fontsize: 1rem
    monofont: courier new
    css: styles.css
    toc: false



